export const hospitals = [
  {
    id: "hosp-1",
    name: "Indraprastha Apollo Hospital | Best Hospital in Delhi",
    address: "Sarita Vihar, Delhi-Mathura Road, New Delhi, Delhi 110076",
    totalBeds: 710,
    availableBeds: 112,
    icuBeds: 120,
    icuAvailable: 18,
    emergencyOccupancy: 68,
    lat: 28.5362,
    lng: 77.2840,
    phone: "+91 (11) 2692-5858",
    rating: 4.8,
    specialties: ["Cardiology", "Trauma Care", "Neurology", "Organ Transplant"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Trauma centers", "Emergency hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 15,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "emergency@indraprastha.apollohospitals.com",
    doctorsAvailableCount: 32
  },
  {
    id: "hosp-2",
    name: "Max Super Speciality Hospital, Saket (Max Saket)",
    address: "1-2, Press Enclave Road, Saket Institutional Area, New Delhi, Delhi 110017",
    totalBeds: 530,
    availableBeds: 85,
    icuBeds: 100,
    icuAvailable: 15,
    emergencyOccupancy: 71,
    lat: 28.5284,
    lng: 77.2120,
    phone: "+91 (11) 2651-5050",
    rating: 4.7,
    specialties: ["Oncology", "Cardiology", "Orthopedics", "Emergency Care"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Cancer hospitals", "Emergency hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 12,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "contact.saket@maxhealthcare.com",
    doctorsAvailableCount: 24
  },
  {
    id: "hosp-3",
    name: "BLK-Max Super Speciality Hospital Delhi",
    address: "Pusa Road, Radha Soami Satsang, Rajendra Place, New Delhi, Delhi 110005",
    totalBeds: 650,
    availableBeds: 92,
    icuBeds: 125,
    icuAvailable: 14,
    emergencyOccupancy: 79,
    lat: 28.6415,
    lng: 77.1782,
    phone: "+91 (11) 3040-3040",
    rating: 4.6,
    specialties: ["Bone Marrow", "Oncology", "Neurology", "Plastic Surgery"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Cancer hospitals", "Emergency hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 10,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "helpdesk@blkmax.com",
    doctorsAvailableCount: 25
  },
  {
    id: "hosp-4",
    name: "Fortis Flt Lt Rajan Dhall Hospital, Vasant Kunj - Best Hospital in New Delhi",
    address: "Aruna Asaf Ali Marg, Sector B, Pocket 1, Vasant Kunj, New Delhi, Delhi 110070",
    totalBeds: 200,
    availableBeds: 45,
    icuBeds: 45,
    icuAvailable: 8,
    emergencyOccupancy: 62,
    lat: 28.5195,
    lng: 77.1585,
    phone: "+91 (11) 4277-6222",
    rating: 4.6,
    specialties: ["Cardiology", "Nephrology", "Joint Replacement", "Emergency Medicine"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Cardiac centers", "Emergency hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 8,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "enquiry.vk@fortishealthcare.com",
    doctorsAvailableCount: 19
  },
  {
    id: "hosp-5",
    name: "Dharamshila Narayana Superspeciality Hospital, Delhi",
    address: "Metro Station Budh Vihar, Dharamshila Marg, Vasundhara Enclave, Delhi 110096",
    totalBeds: 350,
    availableBeds: 58,
    icuBeds: 70,
    icuAvailable: 11,
    emergencyOccupancy: 76,
    lat: 28.6019,
    lng: 77.3242,
    phone: "+91 (11) 4000-1234",
    rating: 4.5,
    specialties: ["Oncology", "Bone Marrow", "Gastroenterology", "Cardiac Care"],
    categories: ["Private hospitals", "Cancer hospitals", "Multi-speciality hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 9,
    isGovernment: false,
    hasTelemedicine: false,
    hasOpdBooking: true,
    email: "help.dnsh@narayanahealth.org",
    doctorsAvailableCount: 21
  },
  {
    id: "hosp-6",
    name: "Primus Super Speciality Hospital",
    address: "Chandragupta Marg, Chanakyapuri, New Delhi, Delhi 110021",
    totalBeds: 250,
    availableBeds: 62,
    icuBeds: 50,
    icuAvailable: 12,
    emergencyOccupancy: 54,
    lat: 28.5959,
    lng: 77.1891,
    phone: "+91 (11) 6620-6620",
    rating: 4.4,
    specialties: ["Orthopedics", "Spine Surgery", "ENT", "Joint Reconstruction"],
    categories: ["Private hospitals", "Multi-speciality hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 6,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "info@primushospital.com",
    doctorsAvailableCount: 16
  },
  {
    id: "hosp-7",
    name: "Aakash Healthcare Super Speciality Hospital",
    address: "Road No. 201, Sector 3, Dwarka, New Delhi, Delhi 110075",
    totalBeds: 300,
    availableBeds: 51,
    icuBeds: 70,
    icuAvailable: 9,
    emergencyOccupancy: 81,
    lat: 28.5961,
    lng: 77.0543,
    phone: "+91 (11) 4388-4388",
    rating: 4.6,
    specialties: ["Emergency Medicine", "Orthopedics", "Cardiology", "Trauma Care"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Trauma centers", "Emergency hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 14,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "reach@aakashhealthcare.com",
    doctorsAvailableCount: 22
  },
  {
    id: "hosp-8",
    name: "CK Birla Hospital, Delhi",
    address: "Block AG, Shalimar Bagh, New Delhi, Delhi 110088",
    totalBeds: 150,
    availableBeds: 34,
    icuBeds: 30,
    icuAvailable: 6,
    emergencyOccupancy: 59,
    lat: 28.7183,
    lng: 77.1590,
    phone: "+91 (11) 4153-2222",
    rating: 4.7,
    specialties: ["Pediatrics", "Neonatology", "Obstetrics & Gynecology", "Fertility"],
    categories: ["Private hospitals", "Pediatric hospitals", "Multi-speciality hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 5,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "delhi@ckbirlahospital.com",
    doctorsAvailableCount: 18
  },
  {
    id: "hosp-9",
    name: "SCI International Hospital",
    address: "M-4, Greater Kailash-I, New Delhi, Delhi 110048",
    totalBeds: 110,
    availableBeds: 29,
    icuBeds: 20,
    icuAvailable: 4,
    emergencyOccupancy: 65,
    lat: 28.5524,
    lng: 77.2345,
    phone: "+91 (11) 4323-4323",
    rating: 4.5,
    specialties: ["Urology", "IVF", "Gynecology", "Minimally Invasive Surgery"],
    categories: ["Private hospitals", "Multi-speciality hospitals"],
    hasAmbulanceSupport: false,
    ambulanceSupportCount: 2,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "info@scihospital.com",
    doctorsAvailableCount: 12
  },
  {
    id: "hosp-10",
    name: "Saroj Super Speciality Hospital",
    address: "Madhuban Chowk, Bhagwan Mahavir Marg, Sector 14, Rohini, Delhi 110085",
    totalBeds: 220,
    availableBeds: 38,
    icuBeds: 50,
    icuAvailable: 5,
    emergencyOccupancy: 83,
    lat: 28.7075,
    lng: 77.1245,
    phone: "+91 (11) 4802-4802",
    rating: 4.3,
    specialties: ["Nephrology", "Urology", "Cardiac Surgery", "Gastroenterology"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Cardiac centers"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 6,
    isGovernment: false,
    hasTelemedicine: false,
    hasOpdBooking: true,
    email: "care@sarojhospital.com",
    doctorsAvailableCount: 15
  },
  {
    id: "hosp-11",
    name: "PSRI Multispeciality Hospital Delhi",
    address: "Press Enclave Marg, JNS Marg, Sheikh Sarai Phase II, New Delhi, Delhi 110017",
    totalBeds: 250,
    availableBeds: 49,
    icuBeds: 60,
    icuAvailable: 8,
    emergencyOccupancy: 72,
    lat: 28.5312,
    lng: 77.2285,
    phone: "+91 (11) 3061-1700",
    rating: 4.5,
    specialties: ["Gastroenterology", "Nephrology", "Urology", "Cardiology"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Cardiac centers"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 7,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "info@psrihospital.com",
    doctorsAvailableCount: 20
  },
  {
    id: "hosp-12",
    name: "AIIMS Delhi",
    address: "Ansari Nagar, Ring Road, New Delhi, Delhi 110029",
    totalBeds: 2200,
    availableBeds: 48,
    icuBeds: 200,
    icuAvailable: 4,
    emergencyOccupancy: 96,
    lat: 28.5672,
    lng: 77.2100,
    phone: "+91 (11) 2658-8500",
    rating: 4.9,
    specialties: ["All Clinical Specialties", "Trauma Surgery", "Oncology", "Pediatric Care"],
    categories: ["Government hospitals", "Multi-speciality hospitals", "Emergency hospitals", "Trauma centers", "Pediatric hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 30,
    isGovernment: true,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "director@aiims.edu",
    doctorsAvailableCount: 150
  },
  {
    id: "hosp-13",
    name: "Medanta - The Medicity",
    address: "CH Baktawar Singh Road, Sector 38, Gurugram, Haryana 122001",
    totalBeds: 1250,
    availableBeds: 180,
    icuBeds: 150,
    icuAvailable: 22,
    emergencyOccupancy: 62,
    lat: 28.4258,
    lng: 77.0422,
    phone: "+91 (124) 414-1414",
    rating: 4.8,
    specialties: ["Cardiology", "Organ Transplant", "Neurology", "Oncology"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Cardiac centers", "Trauma centers", "Emergency hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 25,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "info@medanta.org",
    doctorsAvailableCount: 95
  },
  {
    id: "hosp-14",
    name: "Fortis Escorts Heart Institute",
    address: "Okhla Road, Sukhdev Vihar, New Delhi, Delhi 110025",
    totalBeds: 310,
    availableBeds: 42,
    icuBeds: 80,
    icuAvailable: 8,
    emergencyOccupancy: 78,
    lat: 28.5606,
    lng: 77.2721,
    phone: "+91 (11) 4713-5000",
    rating: 4.7,
    specialties: ["Cardiology", "Cardiac Surgery", "Pediatric Cardiology", "Electrophysiology"],
    categories: ["Private hospitals", "Cardiac centers", "Pediatric hospitals", "Emergency hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 11,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "contact.escorts@fortishealthcare.com",
    doctorsAvailableCount: 40
  },
  {
    id: "hosp-15",
    name: "Sir Ganga Ram Hospital",
    address: "Sir Ganga Ram Hospital Marg, Old Rajinder Nagar, New Delhi, Delhi 110060",
    totalBeds: 675,
    availableBeds: 50,
    icuBeds: 100,
    icuAvailable: 11,
    emergencyOccupancy: 84,
    lat: 28.6384,
    lng: 77.1895,
    phone: "+91 (11) 2575-0000",
    rating: 4.6,
    specialties: ["Laparoscopic Surgery", "Nephrology", "Hepatology", "Pediatric Medicine"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Pediatric hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 10,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "gangaram@sgrh.com",
    doctorsAvailableCount: 50
  },
  {
    id: "hosp-16",
    name: "Artemis Hospital",
    address: "Sector 51, Gurugram, Haryana 122001",
    totalBeds: 400,
    availableBeds: 68,
    icuBeds: 80,
    icuAvailable: 14,
    emergencyOccupancy: 71,
    lat: 28.4310,
    lng: 77.0855,
    phone: "+91 (124) 451-1111",
    rating: 4.6,
    specialties: ["Neurology", "Orthopedics", "Cardiovascular Surgery", "Emergency Medicine"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Emergency hospitals", "Trauma centers"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 12,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "assistance@artemishospitals.com",
    doctorsAvailableCount: 35
  },
  {
    id: "hosp-17",
    name: "Manipal Hospital Dwarka",
    address: "Sector 6, Dwarka, New Delhi, Delhi 110075",
    totalBeds: 380,
    availableBeds: 52,
    icuBeds: 75,
    icuAvailable: 10,
    emergencyOccupancy: 74,
    lat: 28.5912,
    lng: 77.0585,
    phone: "+91 (11) 4967-4967",
    rating: 4.6,
    specialties: ["Emergency Care", "Cardiology", "Oncology", "Renal Sciences"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Emergency hospitals", "Trauma centers"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 10,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "dwarka@manipalhospitals.com",
    doctorsAvailableCount: 30
  },
  {
    id: "hosp-18",
    name: "Moolchand Hospital",
    address: "Lajpat Nagar III, Near Ring Road, New Delhi, Delhi 110024",
    totalBeds: 350,
    availableBeds: 80,
    icuBeds: 50,
    icuAvailable: 15,
    emergencyOccupancy: 53,
    lat: 28.5684,
    lng: 77.2395,
    phone: "+91 (11) 4200-0000",
    rating: 4.5,
    specialties: ["Obstetrics & Gynecology", "Pediatrics", "Joint Replacement", "Internal Medicine"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Pediatric hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 8,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "info@moolchand.com",
    doctorsAvailableCount: 25
  },
  {
    id: "hosp-19",
    name: "Batra Hospital & Medical Research Centre",
    address: "1, Mehrauli - Badarpur Rd, Tuglakabad Institutional Area, New Delhi, Delhi 110062",
    totalBeds: 495,
    availableBeds: 94,
    icuBeds: 80,
    icuAvailable: 16,
    emergencyOccupancy: 61,
    lat: 28.5135,
    lng: 77.2519,
    phone: "+91 (11) 2995-8747",
    rating: 4.4,
    specialties: ["Oncology", "Urology", "Cardiology", "Critical Care"],
    categories: ["Private hospitals", "Cancer hospitals", "Multi-speciality hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 9,
    isGovernment: false,
    hasTelemedicine: false,
    hasOpdBooking: true,
    email: "admin@batrahospital.org",
    doctorsAvailableCount: 22
  },
  {
    id: "hosp-20",
    name: "Venkateshwar Hospital",
    address: "Sector 18A, Dwarka, New Delhi, Delhi 110075",
    totalBeds: 325,
    availableBeds: 71,
    icuBeds: 50,
    icuAvailable: 12,
    emergencyOccupancy: 63,
    lat: 28.5878,
    lng: 77.0398,
    phone: "+91 (11) 4855-5555",
    rating: 4.5,
    specialties: ["Gastroenterology", "Nephrology", "Interventional Cardiology", "Pulmonology"],
    categories: ["Private hospitals", "Multi-speciality hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 6,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "info@venkateshwarhospitals.com",
    doctorsAvailableCount: 19
  },
  {
    id: "hosp-21",
    name: "Holy Family Hospital",
    address: "Okhla Road, Okhla, New Delhi, Delhi 110025",
    totalBeds: 345,
    availableBeds: 54,
    icuBeds: 60,
    icuAvailable: 10,
    emergencyOccupancy: 79,
    lat: 28.5619,
    lng: 77.2758,
    phone: "+91 (11) 2684-5900",
    rating: 4.4,
    specialties: ["Obstetrics & Gynecology", "Pediatrics", "General Surgery", "Asthma Care"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Pediatric hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 8,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "contact@holyfamilydelhi.org",
    doctorsAvailableCount: 23
  },
  {
    id: "hosp-22",
    name: "Safdarjung Hospital",
    address: "Ansari Nagar East, Ring Road, New Delhi, Delhi 110029",
    totalBeds: 2100,
    availableBeds: 32,
    icuBeds: 180,
    icuAvailable: 2,
    emergencyOccupancy: 95,
    lat: 28.5694,
    lng: 77.2082,
    phone: "+91 (11) 2616-5060",
    rating: 4.1,
    specialties: ["Burns and Plastic Surgery", "Trauma Surgery", "Obstetrics", "General Medicine"],
    categories: ["Government hospitals", "Trauma centers", "Emergency hospitals", "Multi-speciality hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 15,
    isGovernment: true,
    hasTelemedicine: false,
    hasOpdBooking: true,
    email: "ms@safdarjunghospital.co.in",
    doctorsAvailableCount: 85
  },
  {
    id: "hosp-23",
    name: "Ram Manohar Lohia Hospital",
    address: "Baba Kharak Singh Marg, Connaught Place, New Delhi, Delhi 110001",
    totalBeds: 1420,
    availableBeds: 41,
    icuBeds: 120,
    icuAvailable: 5,
    emergencyOccupancy: 92,
    lat: 28.6236,
    lng: 77.2012,
    phone: "+91 (11) 2336-5525",
    rating: 4.2,
    specialties: ["Cardiology", "Burn Care", "Emergency Medicine", "General Surgery"],
    categories: ["Government hospitals", "Emergency hospitals", "Multi-speciality hospitals", "Trauma centers"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 10,
    isGovernment: true,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "info@rmlh.nic.in",
    doctorsAvailableCount: 65
  },
  {
    id: "hosp-24",
    name: "Lok Nayak Hospital",
    address: "Jawaharlal Nehru Marg, Near Delhi Gate, New Delhi, Delhi 110002",
    totalBeds: 1590,
    availableBeds: 45,
    icuBeds: 130,
    icuAvailable: 7,
    emergencyOccupancy: 89,
    lat: 28.6360,
    lng: 77.2399,
    phone: "+91 (11) 2323-3400",
    rating: 4.1,
    specialties: ["General Medicine", "Pediatric Surgery", "Orthopedics", "Gynecology"],
    categories: ["Government hospitals", "Multi-speciality hospitals", "Pediatric hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 8,
    isGovernment: true,
    hasTelemedicine: false,
    hasOpdBooking: true,
    email: "mslnh@delhi.gov.in",
    doctorsAvailableCount: 55
  },
  {
    id: "hosp-25",
    name: "St. Stephen’s Hospital",
    address: "St. Stephen's Hospital Marg, Tis Hazari, Delhi 110054",
    totalBeds: 600,
    availableBeds: 65,
    icuBeds: 55,
    icuAvailable: 10,
    emergencyOccupancy: 78,
    lat: 28.6659,
    lng: 77.2185,
    phone: "+91 (11) 2396-6021",
    rating: 4.4,
    specialties: ["Maternity Care", "Pediatric Surgery", "Internal Medicine", "Orthopedics"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Pediatric hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 7,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "contact@ststephenshospital.org",
    doctorsAvailableCount: 26
  },
  {
    id: "hosp-26",
    name: "Maharaja Agrasen Hospital",
    address: "Shashstri Nagar, Near West Punjabi Bagh, New Delhi, Delhi 110026",
    totalBeds: 400,
    availableBeds: 70,
    icuBeds: 60,
    icuAvailable: 12,
    emergencyOccupancy: 67,
    lat: 28.6710,
    lng: 77.1298,
    phone: "+91 (11) 4077-7777",
    rating: 4.3,
    specialties: ["Urology", "Neonatology", "Nephrology", "Interventional Cardiology"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Pediatric hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 8,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "info@mahagrasen.com",
    doctorsAvailableCount: 23
  },
  {
    id: "hosp-27",
    name: "Rajiv Gandhi Cancer Institute",
    address: "Sector 5, Rohini, Delhi 110085",
    totalBeds: 500,
    availableBeds: 45,
    icuBeds: 80,
    icuAvailable: 6,
    emergencyOccupancy: 81,
    lat: 28.7118,
    lng: 77.1190,
    phone: "+91 (11) 4702-2222",
    rating: 4.7,
    specialties: ["Clinical Oncology", "Surgical Oncology", "Hematology", "Bone Marrow Transplant"],
    categories: ["Private hospitals", "Cancer hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 6,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "info@rgcirc.org",
    doctorsAvailableCount: 30
  },
  {
    id: "hosp-28",
    name: "Shalimar Bagh Fortis Hospital",
    address: "AA Block, Shalimar Bagh, New Delhi, Delhi 110088",
    totalBeds: 262,
    availableBeds: 54,
    icuBeds: 50,
    icuAvailable: 9,
    emergencyOccupancy: 74,
    lat: 28.7190,
    lng: 77.1610,
    phone: "+91 (11) 4530-2222",
    rating: 4.5,
    specialties: ["Oncology", "Orthopedics", "Pulmonology", "Cardiac Sciences"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Cancer hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 10,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "enquiry.sb@fortishealthcare.com",
    doctorsAvailableCount: 22
  },
  {
    id: "hosp-29",
    name: "Yashoda Super Speciality Hospital",
    address: "H-1, Kaushambi, Near Anand Vihar, Ghaziabad, Uttar Pradesh 201010",
    totalBeds: 300,
    availableBeds: 51,
    icuBeds: 60,
    icuAvailable: 8,
    emergencyOccupancy: 82,
    lat: 28.6433,
    lng: 77.3195,
    phone: "+91 (120) 418-2000",
    rating: 4.6,
    specialties: ["Trauma Medicine", "Interventional Neurology", "Critical Care", "Gastro Surgery"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Trauma centers", "Emergency hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 11,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "info@yashodahospital.org",
    doctorsAvailableCount: 25
  },
  {
    id: "hosp-30",
    name: "Jaypee Hospital",
    address: "Wish Town, Sector 128, Noida, Uttar Pradesh 201304",
    totalBeds: 505,
    availableBeds: 120,
    icuBeds: 90,
    icuAvailable: 19,
    emergencyOccupancy: 48,
    lat: 28.5134,
    lng: 77.3710,
    phone: "+91 (120) 412-2222",
    rating: 4.7,
    specialties: ["Cardiac Sciences", "Solid Organ Transplant", "Bone Marrow", "IVF"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Cardiac centers", "Emergency hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 14,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "oncall@jaypeehealthcare.com",
    doctorsAvailableCount: 38
  },
  {
    id: "hosp-31",
    name: "Kailash Hospital",
    address: "H-33, Sector 27, Noida, Uttar Pradesh 201301",
    totalBeds: 350,
    availableBeds: 64,
    icuBeds: 60,
    icuAvailable: 11,
    emergencyOccupancy: 81,
    lat: 28.5715,
    lng: 77.3323,
    phone: "+91 (120) 244-4444",
    rating: 4.5,
    specialties: ["Critical Care", "Cardiology", "Trauma and Burns", "Pediatric Surgery"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Emergency hospitals", "Trauma centers"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 12,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "kailash@kailashhospital.com",
    doctorsAvailableCount: 20
  },
  {
    id: "hosp-32",
    name: "Metro Hospital & Heart Institute",
    address: "L-94, Sector 11, Noida, Uttar Pradesh 201301",
    totalBeds: 317,
    availableBeds: 49,
    icuBeds: 50,
    icuAvailable: 9,
    emergencyOccupancy: 76,
    lat: 28.5912,
    lng: 77.3198,
    phone: "+91 (120) 244-2222",
    rating: 4.5,
    specialties: ["Interventional Cardiology", "Cardio Surgery", "Pulmonology", "Critical Care"],
    categories: ["Private hospitals", "Cardiac centers", "Multi-speciality hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 8,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "metro@metrohospitals.com",
    doctorsAvailableCount: 18
  },
  {
    id: "hosp-33",
    name: "Asian Institute of Medical Sciences",
    address: "Sector 21A, Badkal Flyover Road, Faridabad, Haryana 121001",
    totalBeds: 425,
    availableBeds: 74,
    icuBeds: 70,
    icuAvailable: 12,
    emergencyOccupancy: 67,
    lat: 28.4116,
    lng: 77.3015,
    phone: "+91 (129) 425-3000",
    rating: 4.6,
    specialties: ["Biomedical Oncology", "Cardiac Sciences", "Neurology", "Urology"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Cancer hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 10,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "info@aimsindia.com",
    doctorsAvailableCount: 22
  },
  {
    id: "hosp-34",
    name: "Amrita Hospital",
    address: "Sector 88, Faridabad, Haryana 121002",
    totalBeds: 2000,
    availableBeds: 345,
    icuBeds: 150,
    icuAvailable: 29,
    emergencyOccupancy: 42,
    lat: 28.4312,
    lng: 77.3598,
    phone: "+91 (129) 285-8124",
    rating: 4.8,
    specialties: ["Pediatric Cardiology", "Neurosciences", "Gastrointestinal Surgery", "Robotic Care"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Pediatric hospitals", "Trauma centers"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 20,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "fbd@amritahospitals.org",
    doctorsAvailableCount: 60
  },
  {
    id: "hosp-35",
    name: "Cloudnine Hospital",
    address: "Sector 14, Near Kalyani Hospital, Gurugram, Haryana 122001",
    totalBeds: 80,
    availableBeds: 21,
    icuBeds: 20,
    icuAvailable: 5,
    emergencyOccupancy: 52,
    lat: 28.4682,
    lng: 77.0450,
    phone: "+91 (124) 432-8111",
    rating: 4.7,
    specialties: ["Neonatology", "Maternity Wellness", "Pediatrics", "Gynecology"],
    categories: ["Private hospitals", "Pediatric hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 4,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "info@cloudninecare.com",
    doctorsAvailableCount: 15
  },
  {
    id: "hosp-36",
    name: "Paras Hospitals",
    address: "C-1, Sushant Lok-1, Sector 43, Gurugram, Haryana 122043",
    totalBeds: 330,
    availableBeds: 54,
    icuBeds: 60,
    icuAvailable: 10,
    emergencyOccupancy: 78,
    lat: 28.4590,
    lng: 77.0812,
    phone: "+91 (124) 458-5555",
    rating: 4.5,
    specialties: ["Spine Surgery", "Joint Replacement", "Neuro Surgery", "Trauma Medicine"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Trauma centers"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 9,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "contact.gurgaon@parashospitals.com",
    doctorsAvailableCount: 22
  },
  {
    id: "hosp-37",
    name: "Columbia Asia Hospital",
    address: "Ansal Plaza, Sector 23, Gurugram, Haryana 122017",
    totalBeds: 100,
    availableBeds: 22,
    icuBeds: 20,
    icuAvailable: 3,
    emergencyOccupancy: 64,
    lat: 28.5110,
    lng: 77.0425,
    phone: "+91 (124) 398-9896",
    rating: 4.5,
    specialties: ["Internal Medicine", "General Surgery", "Urology", "Pediatrics"],
    categories: ["Private hospitals", "Multi-speciality hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 3,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "care.palam@columbiaasia.com",
    doctorsAvailableCount: 11
  },
  {
    id: "hosp-38",
    name: "Narayana Hospital Gurugram",
    address: "DLF Phase 3, Sector 24, Gurugram, Haryana 122002",
    totalBeds: 220,
    availableBeds: 41,
    icuBeds: 40,
    icuAvailable: 6,
    emergencyOccupancy: 71,
    lat: 28.5100,
    lng: 77.1025,
    phone: "+91 (124) 458-1234",
    rating: 4.6,
    specialties: ["Interventional Cardiology", "Nephrology", "Infectious Diseases", "Joint Care"],
    categories: ["Private hospitals", "Cardiac centers", "Multi-speciality hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 6,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "enquiry.gurugram@narayanahealth.org",
    doctorsAvailableCount: 15
  },
  {
    id: "hosp-39",
    name: "Fortis Memorial Research Institute",
    address: "Sector 44, Opposite HUDA City Centre, Gurugram, Haryana 122002",
    totalBeds: 1000,
    availableBeds: 154,
    icuBeds: 120,
    icuAvailable: 18,
    emergencyOccupancy: 65,
    lat: 28.4526,
    lng: 77.0722,
    phone: "+91 (124) 496-2200",
    rating: 4.8,
    specialties: ["Robotic Transplants", "Neuro-Oncology", "Hematology", "Reproduction IVF"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Cancer hospitals", "Emergency hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 22,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "fmri@fortishealthcare.com",
    doctorsAvailableCount: 75
  },
  {
    id: "hosp-40",
    name: "Max Hospital Vaishali",
    address: "W-3, Sector 1, Vaishali, Ghaziabad, Uttar Pradesh 201012",
    totalBeds: 370,
    availableBeds: 58,
    icuBeds: 60,
    icuAvailable: 8,
    emergencyOccupancy: 81,
    lat: 28.6416,
    lng: 77.3370,
    phone: "+91 (120) 418-8000",
    rating: 4.6,
    specialties: ["Emergency Medicine", "Cardiac Sciences", "Joint Reconstruction", "Trauma Resection"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Emergency hospitals", "Trauma centers"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 12,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "care.vaishali@maxhealthcare.com",
    doctorsAvailableCount: 24
  },
  {
    id: "hosp-41",
    name: "Felix Hospital",
    address: "Sector 137, Expressway, Noida, Uttar Pradesh 201305",
    totalBeds: 180,
    availableBeds: 45,
    icuBeds: 30,
    icuAvailable: 5,
    emergencyOccupancy: 58,
    lat: 28.5126,
    lng: 77.4019,
    phone: "+91 (120) 314-5555",
    rating: 4.4,
    specialties: ["Preventive Health", "Obstetrics & Gynecology", "Pediatrics", "Cardiology"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Pediatric hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 6,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "info@felixhospital.com",
    doctorsAvailableCount: 16
  },
  {
    id: "hosp-42",
    name: "Sharda Hospital",
    address: "Plot No. 32, 34, Knowledge Park III, Greater Noida, Uttar Pradesh 201306",
    totalBeds: 900,
    availableBeds: 145,
    icuBeds: 90,
    icuAvailable: 23,
    emergencyOccupancy: 48,
    lat: 28.4731,
    lng: 77.4839,
    phone: "+91 (120) 232-9700",
    rating: 4.4,
    specialties: ["Emergency Medicine", "Orthopedics & Joint Care", "Burn Care", "Internal Medicine"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Trauma centers", "Emergency hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 14,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "info@shardahospital.org",
    doctorsAvailableCount: 45
  },
  {
    id: "hosp-43",
    name: "Apollo Spectra Hospital",
    address: "Kailash Colony, Greater Kailash I, New Delhi, Delhi 110048",
    totalBeds: 95,
    availableBeds: 20,
    icuBeds: 15,
    icuAvailable: 4,
    emergencyOccupancy: 61,
    lat: 28.5520,
    lng: 77.2450,
    phone: "+91 (11) 4004-3300",
    rating: 4.5,
    specialties: ["Minimally Invasive Surgery", "Cosmetic Surgery", "Gastroenterology", "Ophthalmology"],
    categories: ["Private hospitals", "Multi-speciality hospitals"],
    hasAmbulanceSupport: false,
    ambulanceSupportCount: 1,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "contact@apollospectra.com",
    doctorsAvailableCount: 12
  },
  {
    id: "hosp-44",
    name: "Deep Chand Bandhu Hospital",
    address: "Kokiwala Bagh, Ashok Vihar, Phase IV, New Delhi, Delhi 110052",
    totalBeds: 210,
    availableBeds: 24,
    icuBeds: 20,
    icuAvailable: 2,
    emergencyOccupancy: 88,
    lat: 28.6912,
    lng: 77.1700,
    phone: "+91 (11) 2730-5950",
    rating: 4.0,
    specialties: ["General Medicine", "Pediatrics Outpatient", "Maternity Triage"],
    categories: ["Government hospitals", "Multi-speciality hospitals", "Pediatric hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 5,
    isGovernment: true,
    hasTelemedicine: false,
    hasOpdBooking: true,
    email: "msdcbh@delhi.gov.in",
    doctorsAvailableCount: 16
  },
  {
    id: "hosp-45",
    name: "Deen Dayal Upadhyay Hospital",
    address: "Hari Nagar, Near Clock Tower, New Delhi, Delhi 110064",
    totalBeds: 640,
    availableBeds: 45,
    icuBeds: 50,
    icuAvailable: 3,
    emergencyOccupancy: 91,
    lat: 28.6291,
    lng: 77.1082,
    phone: "+91 (11) 2549-4401",
    rating: 4.1,
    specialties: ["Forensic Medicine", "Emergency General Surgery", "Orthopedics", "Trauma Triage"],
    categories: ["Government hospitals", "Trauma centers", "Emergency hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 8,
    isGovernment: true,
    hasTelemedicine: false,
    hasOpdBooking: true,
    email: "msdduh@delhi.gov.in",
    doctorsAvailableCount: 30
  },
  {
    id: "hosp-46",
    name: "Guru Teg Bahadur Hospital",
    address: "Shahdara, Dilshad Garden, Delhi 110095",
    totalBeds: 1500,
    availableBeds: 50,
    icuBeds: 120,
    icuAvailable: 4,
    emergencyOccupancy: 94,
    lat: 28.6833,
    lng: 77.3090,
    phone: "+91 (11) 2258-2972",
    rating: 4.1,
    specialties: ["Specialist Traumatology", "Surgical Burns Care", "Critical Care Resus"],
    categories: ["Government hospitals", "Multi-speciality hospitals", "Emergency hospitals", "Trauma centers"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 15,
    isGovernment: true,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "msgtbh@delhi.gov.in",
    doctorsAvailableCount: 75
  },
  {
    id: "hosp-47",
    name: "ESIC Hospital Basaidarapur",
    address: "Ring Road, Near Basaidarapur metro, New Delhi, Delhi 110015",
    totalBeds: 600,
    availableBeds: 94,
    icuBeds: 50,
    icuAvailable: 8,
    emergencyOccupancy: 79,
    lat: 28.6534,
    lng: 77.1350,
    phone: "+91 (11) 2597-0951",
    rating: 4.2,
    specialties: ["Occupational Health Diseases", "General Surgery", "Cardiology Clinic"],
    categories: ["Government hospitals", "Multi-speciality hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 6,
    isGovernment: true,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "ms-basaidarapur.dl@esic.nic.in",
    doctorsAvailableCount: 35
  },
  {
    id: "hosp-48",
    name: "Bhagwan Mahavir Hospital",
    address: "H-4, Pitampura, Ring Road, Delhi 110034",
    totalBeds: 280,
    availableBeds: 35,
    icuBeds: 20,
    icuAvailable: 2,
    emergencyOccupancy: 86,
    lat: 28.7011,
    lng: 77.1290,
    phone: "+91 (11) 2715-9850",
    rating: 4.0,
    specialties: ["General Maternity", "Standard Outpatient Triage", "Pediatrics Care"],
    categories: ["Government hospitals", "Multi-speciality hospitals", "Pediatric hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 5,
    isGovernment: true,
    hasTelemedicine: false,
    hasOpdBooking: true,
    email: "bmh.delhi@nic.in",
    doctorsAvailableCount: 18
  },
  {
    id: "hosp-49",
    name: "Mata Chanan Devi Hospital",
    address: "C1 Block, Janakpuri, New Delhi, Delhi 110058",
    totalBeds: 300,
    availableBeds: 42,
    icuBeds: 40,
    icuAvailable: 6,
    emergencyOccupancy: 81,
    lat: 28.6212,
    lng: 77.0858,
    phone: "+91 (11) 4566-6666",
    rating: 4.3,
    specialties: ["Gynecological Endoscopy", "General Surgery", "Clinical Pediatrics"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Pediatric hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 7,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "mcdh@vsnl.com",
    doctorsAvailableCount: 20
  },
  {
    id: "hosp-50",
    name: "Tirath Ram Shah Hospital",
    address: "2, Battery Lane, Rajpur Road, Civil Lines, Delhi 110054",
    totalBeds: 200,
    availableBeds: 38,
    icuBeds: 20,
    icuAvailable: 3,
    emergencyOccupancy: 70,
    lat: 28.6812,
    lng: 77.2215,
    phone: "+91 (11) 2397-2425",
    rating: 4.2,
    specialties: ["Standard Inpatient care", "Emergency ENT Triage", "Physiotherapy"],
    categories: ["Private hospitals", "Multi-speciality hospitals"],
    hasAmbulanceSupport: false,
    ambulanceSupportCount: 2,
    isGovernment: false,
    hasTelemedicine: false,
    hasOpdBooking: true,
    email: "tirathramshahhospital@gmail.com",
    doctorsAvailableCount: 12
  },
  {
    id: "hosp-51",
    name: "Kalra Hospital",
    address: "A-4, Kirti Nagar, New Delhi, Delhi 110015",
    totalBeds: 250,
    availableBeds: 51,
    icuBeds: 35,
    icuAvailable: 6,
    emergencyOccupancy: 73,
    lat: 28.6530,
    lng: 77.1420,
    phone: "+91 (11) 4500-4500",
    rating: 4.3,
    specialties: ["Critical Care ICU", "Orthopedic Joint Care", "Therapeutic Nephrology"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Emergency hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 7,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "kalrahospital@rediffmail.com",
    doctorsAvailableCount: 19
  },
  {
    id: "hosp-52",
    name: "Sir HN Reliance Hospital Delhi Center",
    address: "Asaf Ali Rd, Turkman Gate, Chandni Chowk, New Delhi, Delhi 110002",
    totalBeds: 200,
    availableBeds: 54,
    icuBeds: 40,
    icuAvailable: 10,
    emergencyOccupancy: 59,
    lat: 28.6412,
    lng: 77.2315,
    phone: "+91 (11) 3212-3212",
    rating: 4.8,
    specialties: ["Cardiac Electrophysiology", "Robotic Knee Replacements", "Neuro sciences"],
    categories: ["Private hospitals", "Multi-speciality hospitals", "Cardiac centers", "Emergency hospitals"],
    hasAmbulanceSupport: true,
    ambulanceSupportCount: 8,
    isGovernment: false,
    hasTelemedicine: true,
    hasOpdBooking: true,
    email: "info.delhi@rfhospital.org",
    doctorsAvailableCount: 15
  }
];

export const doctors = [
  // === CARDIOLOGISTS ===
  {
    id: "doc-2",
    name: "Dr. Naresh Trehan",
    specialty: "Cardiologist",
    rating: 5.0,
    experience: 38,
    patientsServed: 28000,
    online: true,
    queueCount: 5,
    hospitalName: "Medanta - The Medicity",
    waitTimeMin: 22,
    imageUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-7",
    name: "Dr. Ashok Seth",
    specialty: "Cardiologist",
    rating: 4.9,
    experience: 39,
    patientsServed: 35000,
    online: true,
    queueCount: 2,
    hospitalName: "Fortis Escorts Heart Institute",
    waitTimeMin: 15,
    imageUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-8",
    name: "Dr. Balbir Singh",
    specialty: "Cardiologist",
    rating: 4.8,
    experience: 33,
    patientsServed: 24000,
    online: true,
    queueCount: 1,
    hospitalName: "Max Super Speciality Hospital, Saket (Max Saket)",
    waitTimeMin: 10,
    imageUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-9",
    name: "Dr. Purushottam Lal",
    specialty: "Cardiologist",
    rating: 4.9,
    experience: 37,
    patientsServed: 31000,
    online: false,
    queueCount: 0,
    hospitalName: "Metro Hospital & Heart Institute",
    waitTimeMin: 0,
    imageUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-10",
    name: "Dr. K.K. Talwar",
    specialty: "Cardiologist",
    rating: 4.9,
    experience: 40,
    patientsServed: 35000,
    online: true,
    queueCount: 4,
    hospitalName: "BLK-Max Super Speciality Hospital Delhi",
    waitTimeMin: 25,
    imageUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-11",
    name: "Dr. Subhash Chandra",
    specialty: "Cardiologist",
    rating: 4.7,
    experience: 30,
    patientsServed: 19000,
    online: true,
    queueCount: 3,
    hospitalName: "BLK-Max Super Speciality Hospital Delhi",
    waitTimeMin: 18,
    imageUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-12",
    name: "Dr. T.S. Kler",
    specialty: "Cardiologist",
    rating: 4.8,
    experience: 36,
    patientsServed: 27000,
    online: true,
    queueCount: 2,
    hospitalName: "Fortis Memorial Research Institute",
    waitTimeMin: 15,
    imageUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-13",
    name: "Dr. Rajiv Parakh",
    specialty: "Cardiologist",
    rating: 4.8,
    experience: 34,
    patientsServed: 22000,
    online: true,
    queueCount: 2,
    hospitalName: "Medanta - The Medicity",
    waitTimeMin: 10,
    imageUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-14",
    name: "Dr. Sanjeev Gera",
    specialty: "Cardiologist",
    rating: 4.7,
    experience: 25,
    patientsServed: 18000,
    online: false,
    queueCount: 0,
    hospitalName: "Fortis Memorial Research Institute",
    waitTimeMin: 0,
    imageUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-15",
    name: "Dr. Nidhi S. Sharma",
    specialty: "Cardiologist",
    rating: 4.8,
    experience: 18,
    patientsServed: 12000,
    online: true,
    queueCount: 1,
    hospitalName: "Indraprastha Apollo Hospital | Best Hospital in Delhi",
    waitTimeMin: 15,
    imageUrl: "https://images.unsplash.com/photo-1594824813573-246434de83fb?w=150&auto=format&fit=crop&q=80"
  },

  // === PULMONOLOGISTS ===
  {
    id: "doc-5",
    name: "Dr. Arvind Kumar",
    specialty: "Pulmonologist",
    rating: 4.9,
    experience: 28,
    patientsServed: 19500,
    online: true,
    queueCount: 4,
    hospitalName: "Medanta - The Medicity",
    waitTimeMin: 20,
    imageUrl: "https://images.unsplash.com/photo-1527613426441-4da17471b66d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-16",
    name: "Dr. Randeep Guleria",
    specialty: "Pulmonologist",
    rating: 5.0,
    experience: 39,
    patientsServed: 42000,
    online: true,
    queueCount: 5,
    hospitalName: "Medanta - The Medicity",
    waitTimeMin: 35,
    imageUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-17",
    name: "Dr. Sandeep Nayar",
    specialty: "Pulmonologist",
    rating: 4.8,
    experience: 26,
    patientsServed: 19000,
    online: true,
    queueCount: 3,
    hospitalName: "BLK-Max Super Speciality Hospital Delhi",
    waitTimeMin: 15,
    imageUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-18",
    name: "Dr. Rajesh Chawla",
    specialty: "Pulmonologist",
    rating: 4.7,
    experience: 31,
    patientsServed: 21000,
    online: false,
    queueCount: 0,
    hospitalName: "Indraprastha Apollo Hospital | Best Hospital in Delhi",
    waitTimeMin: 0,
    imageUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-19",
    name: "Dr. Vivek Nangia",
    specialty: "Pulmonologist",
    rating: 4.8,
    experience: 24,
    patientsServed: 15000,
    online: true,
    queueCount: 2,
    hospitalName: "Max Super Speciality Hospital, Saket (Max Saket)",
    waitTimeMin: 18,
    imageUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-20",
    name: "Dr. Manoj K. Goel",
    specialty: "Pulmonologist",
    rating: 4.8,
    experience: 25,
    patientsServed: 16000,
    online: true,
    queueCount: 2,
    hospitalName: "Fortis Memorial Research Institute",
    waitTimeMin: 12,
    imageUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-21",
    name: "Dr. Avdhesh Bansal",
    specialty: "Pulmonologist",
    rating: 4.6,
    experience: 22,
    patientsServed: 13000,
    online: true,
    queueCount: 1,
    hospitalName: "Indraprastha Apollo Hospital | Best Hospital in Delhi",
    waitTimeMin: 22,
    imageUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-22",
    name: "Dr. Neeraj Gupta",
    specialty: "Pulmonologist",
    rating: 4.7,
    experience: 20,
    patientsServed: 11000,
    online: true,
    queueCount: 2,
    hospitalName: "Sir Ganga Ram Hospital",
    waitTimeMin: 15,
    imageUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-23",
    name: "Dr. Pranav Sharma",
    specialty: "Pulmonologist",
    rating: 4.5,
    experience: 15,
    patientsServed: 9500,
    online: true,
    queueCount: 1,
    hospitalName: "Artemis Hospital",
    waitTimeMin: 10,
    imageUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-24",
    name: "Dr. Sheetal Chaurasia",
    specialty: "Pulmonologist",
    rating: 4.6,
    experience: 14,
    patientsServed: 8800,
    online: true,
    queueCount: 1,
    hospitalName: "Manipal Hospital Dwarka",
    waitTimeMin: 12,
    imageUrl: "https://images.unsplash.com/photo-1594824813573-246434de83fb?w=150&auto=format&fit=crop&q=80"
  },

  // === GASTROENTEROLOGISTS ===
  {
    id: "doc-25",
    name: "Dr. Randhir Sud",
    specialty: "Gastroenterologist",
    rating: 4.9,
    experience: 41,
    patientsServed: 35000,
    online: true,
    queueCount: 4,
    hospitalName: "Medanta - The Medicity",
    waitTimeMin: 25,
    imageUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-26",
    name: "Dr. Anil Arora",
    specialty: "Gastroenterologist",
    rating: 4.9,
    experience: 35,
    patientsServed: 28000,
    online: true,
    queueCount: 3,
    hospitalName: "Sir Ganga Ram Hospital",
    waitTimeMin: 20,
    imageUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-27",
    name: "Dr. Ajay Kumar",
    specialty: "Gastroenterologist",
    rating: 4.8,
    experience: 38,
    patientsServed: 26000,
    online: false,
    queueCount: 0,
    hospitalName: "BLK-Max Super Speciality Hospital Delhi",
    waitTimeMin: 0,
    imageUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-28",
    name: "Dr. Gourdas Choudhuri",
    specialty: "Gastroenterologist",
    rating: 4.8,
    experience: 36,
    patientsServed: 24000,
    online: true,
    queueCount: 2,
    hospitalName: "Fortis Memorial Research Institute",
    waitTimeMin: 18,
    imageUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-29",
    name: "Dr. Subhash Gupta",
    specialty: "Gastroenterologist",
    rating: 4.9,
    experience: 32,
    patientsServed: 20000,
    online: true,
    queueCount: 3,
    hospitalName: "Max Super Speciality Hospital, Saket (Max Saket)",
    waitTimeMin: 22,
    imageUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-30",
    name: "Dr. Shiv Sarin",
    specialty: "Gastroenterologist",
    rating: 5.0,
    experience: 42,
    patientsServed: 39000,
    online: true,
    queueCount: 5,
    hospitalName: "AIIMS Delhi",
    waitTimeMin: 40,
    imageUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-31",
    name: "Dr. Amarender Singh Puri",
    specialty: "Gastroenterologist",
    rating: 4.7,
    experience: 33,
    patientsServed: 18500,
    online: true,
    queueCount: 1,
    hospitalName: "Medanta - The Medicity",
    waitTimeMin: 15,
    imageUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-32",
    name: "Dr. Naresh Bansal",
    specialty: "Gastroenterologist",
    rating: 4.8,
    experience: 21,
    patientsServed: 14000,
    online: true,
    queueCount: 2,
    hospitalName: "Sir Ganga Ram Hospital",
    waitTimeMin: 10,
    imageUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-33",
    name: "Dr. Deepansh Mukim",
    specialty: "Gastroenterologist",
    rating: 4.6,
    experience: 12,
    patientsServed: 6000,
    online: true,
    queueCount: 1,
    hospitalName: "Max Super Speciality Hospital, Saket (Max Saket)",
    waitTimeMin: 12,
    imageUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-34",
    name: "Dr. Shalu Khanna",
    specialty: "Gastroenterologist",
    rating: 4.7,
    experience: 16,
    patientsServed: 9200,
    online: true,
    queueCount: 1,
    hospitalName: "Fortis Flt Lt Rajan Dhall Hospital, Vasant Kunj - Best Hospital in New Delhi",
    waitTimeMin: 12,
    imageUrl: "https://images.unsplash.com/photo-1594824813573-246434de83fb?w=150&auto=format&fit=crop&q=80"
  },

  // === NEUROLOGISTS ===
  {
    id: "doc-3",
    name: "Dr. Sandeep Vaishya",
    specialty: "Neurologist",
    rating: 4.9,
    experience: 27,
    patientsServed: 19000,
    online: true,
    queueCount: 3,
    hospitalName: "Fortis Memorial Research Institute",
    waitTimeMin: 15,
    imageUrl: "https://images.unsplash.com/photo-1594824813573-246434de83fb?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-35",
    name: "Dr. Mukul Varma",
    specialty: "Neurologist",
    rating: 4.8,
    experience: 32,
    patientsServed: 21000,
    online: true,
    queueCount: 2,
    hospitalName: "Indraprastha Apollo Hospital | Best Hospital in Delhi",
    waitTimeMin: 20,
    imageUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-36",
    name: "Dr. Praveen Gupta",
    specialty: "Neurologist",
    rating: 4.9,
    experience: 22,
    patientsServed: 17500,
    online: true,
    queueCount: 2,
    hospitalName: "Fortis Memorial Research Institute",
    waitTimeMin: 10,
    imageUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-37",
    name: "Dr. J.D. Mukherji",
    specialty: "Neurologist",
    rating: 4.8,
    experience: 31,
    patientsServed: 23000,
    online: false,
    queueCount: 0,
    hospitalName: "Max Super Speciality Hospital, Saket (Max Saket)",
    waitTimeMin: 0,
    imageUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-38",
    name: "Dr. P.K. Sachdeva",
    specialty: "Neurologist",
    rating: 4.7,
    experience: 24,
    patientsServed: 15000,
    online: true,
    queueCount: 1,
    hospitalName: "Venkateshwar Hospital",
    waitTimeMin: 12,
    imageUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-39",
    name: "Dr. V.S. Mehta",
    specialty: "Neurologist",
    rating: 4.9,
    experience: 40,
    patientsServed: 31000,
    online: true,
    queueCount: 4,
    hospitalName: "Paras Hospitals",
    waitTimeMin: 30,
    imageUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-40",
    name: "Dr. Arun Saroha",
    specialty: "Neurologist",
    rating: 4.8,
    experience: 23,
    patientsServed: 16000,
    online: true,
    queueCount: 2,
    hospitalName: "Max Hospital Vaishali",
    waitTimeMin: 15,
    imageUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-41",
    name: "Dr. Shamsher Dwivedee",
    specialty: "Neurologist",
    rating: 4.8,
    experience: 29,
    patientsServed: 18000,
    online: true,
    queueCount: 2,
    hospitalName: "BLK-Max Super Speciality Hospital Delhi",
    waitTimeMin: 22,
    imageUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-42",
    name: "Dr. Anand Kumar Saxena",
    specialty: "Neurologist",
    rating: 4.7,
    experience: 25,
    patientsServed: 14500,
    online: true,
    queueCount: 1,
    hospitalName: "Max Super Speciality Hospital, Saket (Max Saket)",
    waitTimeMin: 15,
    imageUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-43",
    name: "Dr. Anita Goel",
    specialty: "Neurologist",
    rating: 4.7,
    experience: 19,
    patientsServed: 9800,
    online: true,
    queueCount: 1,
    hospitalName: "Sir Ganga Ram Hospital",
    waitTimeMin: 10,
    imageUrl: "https://images.unsplash.com/photo-1594824813573-246434de83fb?w=150&auto=format&fit=crop&q=80"
  },

  // === PEDIATRICIANS ===
  {
    id: "doc-4",
    name: "Dr. Sharda Sharma",
    specialty: "Pediatrician",
    rating: 4.9,
    experience: 21,
    patientsServed: 15500,
    online: true,
    queueCount: 2,
    hospitalName: "Fortis Escorts Heart Institute",
    waitTimeMin: 10,
    imageUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-44",
    name: "Dr. Anupam Sibal",
    specialty: "Pediatrician",
    rating: 4.9,
    experience: 31,
    patientsServed: 26000,
    online: true,
    queueCount: 3,
    hospitalName: "Indraprastha Apollo Hospital | Best Hospital in Delhi",
    waitTimeMin: 20,
    imageUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-45",
    name: "Dr. Krishan Chugh",
    specialty: "Pediatrician",
    rating: 5.0,
    experience: 38,
    patientsServed: 32000,
    online: true,
    queueCount: 4,
    hospitalName: "Fortis Memorial Research Institute",
    waitTimeMin: 15,
    imageUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-46",
    name: "Dr. Arvind Taneja",
    specialty: "Pediatrician",
    rating: 4.9,
    experience: 43,
    patientsServed: 38000,
    online: true,
    queueCount: 3,
    hospitalName: "Max Super Speciality Hospital, Saket (Max Saket)",
    waitTimeMin: 25,
    imageUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-47",
    name: "Dr. Neelam Mohan",
    specialty: "Pediatrician",
    rating: 4.8,
    experience: 28,
    patientsServed: 21000,
    online: true,
    queueCount: 2,
    hospitalName: "Medanta - The Medicity",
    waitTimeMin: 20,
    imageUrl: "https://images.unsplash.com/photo-1594824813573-246434de83fb?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-48",
    name: "Dr. Vikas Kohli",
    specialty: "Pediatrician",
    rating: 4.7,
    experience: 26,
    patientsServed: 18500,
    online: false,
    queueCount: 0,
    hospitalName: "Apollo Spectra Hospital",
    waitTimeMin: 0,
    imageUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-49",
    name: "Dr. Rahul Nagpal",
    specialty: "Pediatrician",
    rating: 4.8,
    experience: 25,
    patientsServed: 19000,
    online: true,
    queueCount: 2,
    hospitalName: "Fortis Flt Lt Rajan Dhall Hospital, Vasant Kunj - Best Hospital in New Delhi",
    waitTimeMin: 12,
    imageUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-50",
    name: "Dr. Shaji Thomas John",
    specialty: "Pediatrician",
    rating: 4.7,
    experience: 29,
    patientsServed: 22000,
    online: true,
    queueCount: 2,
    hospitalName: "Moolchand Hospital",
    waitTimeMin: 10,
    imageUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-51",
    name: "Dr. Reema Kumar",
    specialty: "Pediatrician",
    rating: 4.8,
    experience: 16,
    patientsServed: 11000,
    online: true,
    queueCount: 1,
    hospitalName: "CK Birla Hospital, Delhi",
    waitTimeMin: 15,
    imageUrl: "https://images.unsplash.com/photo-1594824813573-246434de83fb?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-52",
    name: "Dr. Amit Gupta",
    specialty: "Pediatrician",
    rating: 4.6,
    experience: 18,
    patientsServed: 12500,
    online: true,
    queueCount: 1,
    hospitalName: "Manipal Hospital Dwarka",
    waitTimeMin: 20,
    imageUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80"
  },

  // === ONCOLOGISTS ===
  {
    id: "doc-53",
    name: "Dr. Harit Chaturvedi",
    specialty: "Oncologist",
    rating: 4.9,
    experience: 33,
    patientsServed: 22000,
    online: true,
    queueCount: 3,
    hospitalName: "Max Super Speciality Hospital, Saket (Max Saket)",
    waitTimeMin: 30,
    imageUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-54",
    name: "Dr. Subodh Chandra Pande",
    specialty: "Oncologist",
    rating: 4.8,
    experience: 36,
    patientsServed: 19500,
    online: true,
    queueCount: 2,
    hospitalName: "Artemis Hospital",
    waitTimeMin: 15,
    imageUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-55",
    name: "Dr. Vinod Raina",
    specialty: "Oncologist",
    rating: 4.9,
    experience: 39,
    patientsServed: 27000,
    online: true,
    queueCount: 3,
    hospitalName: "Fortis Memorial Research Institute",
    waitTimeMin: 25,
    imageUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-56",
    name: "Dr. Pramod Kumar Julka",
    specialty: "Oncologist",
    rating: 4.9,
    experience: 41,
    patientsServed: 33000,
    online: false,
    queueCount: 0,
    hospitalName: "Max Super Speciality Hospital, Saket (Max Saket)",
    waitTimeMin: 0,
    imageUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-57",
    name: "Dr. S.H. Advani",
    specialty: "Oncologist",
    rating: 5.0,
    experience: 46,
    patientsServed: 41000,
    online: true,
    queueCount: 5,
    hospitalName: "Indraprastha Apollo Hospital | Best Hospital in Delhi",
    waitTimeMin: 40,
    imageUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-58",
    name: "Dr. Kapil Kumar",
    specialty: "Oncologist",
    rating: 4.8,
    experience: 30,
    patientsServed: 18000,
    online: true,
    queueCount: 2,
    hospitalName: "BLK-Max Super Speciality Hospital Delhi",
    waitTimeMin: 20,
    imageUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-59",
    name: "Dr. Rajesh Mistry",
    specialty: "Oncologist",
    rating: 4.7,
    experience: 28,
    patientsServed: 16500,
    online: true,
    queueCount: 2,
    hospitalName: "Max Hospital Vaishali",
    waitTimeMin: 15,
    imageUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-60",
    name: "Dr. Sunita Saxena",
    specialty: "Oncologist",
    rating: 4.7,
    experience: 25,
    patientsServed: 14000,
    online: true,
    queueCount: 1,
    hospitalName: "Rajiv Gandhi Cancer Institute",
    waitTimeMin: 10,
    imageUrl: "https://images.unsplash.com/photo-1594824813573-246434de83fb?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-61",
    name: "Dr. Ramesh Sarin",
    specialty: "Oncologist",
    rating: 4.9,
    experience: 42,
    patientsServed: 29000,
    online: true,
    queueCount: 4,
    hospitalName: "Indraprastha Apollo Hospital | Best Hospital in Delhi",
    waitTimeMin: 30,
    imageUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-62",
    name: "Dr. Preeti Chaturvedi",
    specialty: "Oncologist",
    rating: 4.8,
    experience: 17,
    patientsServed: 9500,
    online: true,
    queueCount: 1,
    hospitalName: "Dharamshila Narayana Superspeciality Hospital, Delhi",
    waitTimeMin: 15,
    imageUrl: "https://images.unsplash.com/photo-1594824813573-246434de83fb?w=150&auto=format&fit=crop&q=80"
  },

  // === EMERGENCY MEDICINE ===
  {
    id: "doc-6",
    name: "Dr. Meera Vasudevan",
    specialty: "Emergency Care Physician",
    rating: 4.9,
    experience: 15,
    patientsServed: 8500,
    online: true,
    queueCount: 1,
    hospitalName: "AIIMS Delhi",
    waitTimeMin: 5,
    imageUrl: "https://images.unsplash.com/photo-1637059824899-a441006a6875?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-63",
    name: "Dr. Tamorish Kole",
    specialty: "Emergency Care Physician",
    rating: 4.9,
    experience: 21,
    patientsServed: 18000,
    online: true,
    queueCount: 2,
    hospitalName: "Max Super Speciality Hospital, Saket (Max Saket)",
    waitTimeMin: 5,
    imageUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-64",
    name: "Dr. Sanjeev Bhoi",
    specialty: "Emergency Care Physician",
    rating: 4.8,
    experience: 24,
    patientsServed: 25000,
    online: true,
    queueCount: 3,
    hospitalName: "AIIMS Delhi",
    waitTimeMin: 5,
    imageUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-65",
    name: "Dr. Priyadarshi Ranjan",
    specialty: "Emergency Care Physician",
    rating: 4.7,
    experience: 18,
    patientsServed: 13000,
    online: true,
    queueCount: 1,
    hospitalName: "Fortis Memorial Research Institute",
    waitTimeMin: 5,
    imageUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-66",
    name: "Dr. Narendra Nath Khanna",
    specialty: "Emergency Care Physician",
    rating: 4.8,
    experience: 30,
    patientsServed: 22000,
    online: false,
    queueCount: 0,
    hospitalName: "Indraprastha Apollo Hospital | Best Hospital in Delhi",
    waitTimeMin: 0,
    imageUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-67",
    name: "Dr. S.K.S. Marya",
    specialty: "Emergency Care Physician",
    rating: 4.8,
    experience: 35,
    patientsServed: 29000,
    online: true,
    queueCount: 2,
    hospitalName: "Max Hospital Vaishali",
    waitTimeMin: 10,
    imageUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-68",
    name: "Dr. Ajay Swaroop",
    specialty: "Emergency Care Physician",
    rating: 4.9,
    experience: 36,
    patientsServed: 31000,
    online: true,
    queueCount: 3,
    hospitalName: "Sir Ganga Ram Hospital",
    waitTimeMin: 5,
    imageUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-69",
    name: "Dr. Lalit Bhasin",
    specialty: "Emergency Care Physician",
    rating: 4.7,
    experience: 20,
    patientsServed: 15000,
    online: true,
    queueCount: 2,
    hospitalName: "BLK-Max Super Speciality Hospital Delhi",
    waitTimeMin: 5,
    imageUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-70",
    name: "Dr. Arpana Singh",
    specialty: "Emergency Care Physician",
    rating: 4.7,
    experience: 13,
    patientsServed: 11000,
    online: true,
    queueCount: 1,
    hospitalName: "Aakash Healthcare Super Speciality Hospital",
    waitTimeMin: 5,
    imageUrl: "https://images.unsplash.com/photo-1594824813573-246434de83fb?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-71",
    name: "Dr. Gaurav Sharma",
    specialty: "Emergency Care Physician",
    rating: 4.6,
    experience: 12,
    patientsServed: 9800,
    online: true,
    queueCount: 1,
    hospitalName: "Kailash Hospital",
    waitTimeMin: 5,
    imageUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80"
  },

  // === GENERAL PHYSICIANS ===
  {
    id: "doc-1",
    name: "Dr. Rajesh Sharma",
    specialty: "General Physician",
    rating: 4.9,
    experience: 24,
    patientsServed: 15400,
    online: true,
    queueCount: 3,
    hospitalName: "AIIMS Delhi",
    waitTimeMin: 12,
    imageUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-72",
    name: "Dr. R.P. Singh",
    specialty: "General Physician",
    rating: 4.8,
    experience: 32,
    patientsServed: 29000,
    online: true,
    queueCount: 4,
    hospitalName: "Sir Ganga Ram Hospital",
    waitTimeMin: 15,
    imageUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-73",
    name: "Dr. Sushant Aggarwal",
    specialty: "General Physician",
    rating: 4.8,
    experience: 18,
    patientsServed: 13000,
    online: true,
    queueCount: 2,
    hospitalName: "Medanta - The Medicity",
    waitTimeMin: 12,
    imageUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-74",
    name: "Dr. Sanjay Mahajan",
    specialty: "General Physician",
    rating: 4.8,
    experience: 24,
    patientsServed: 19500,
    online: true,
    queueCount: 3,
    hospitalName: "Max Super Speciality Hospital, Saket (Max Saket)",
    waitTimeMin: 15,
    imageUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-75",
    name: "Dr. S.C.L. Gupta",
    specialty: "General Physician",
    rating: 4.7,
    experience: 38,
    patientsServed: 34005,
    online: false,
    queueCount: 0,
    hospitalName: "Batra Hospital & Medical Research Centre",
    waitTimeMin: 0,
    imageUrl: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-76",
    name: "Dr. Anjali Hooda",
    specialty: "General Physician",
    rating: 4.9,
    experience: 15,
    patientsServed: 11500,
    online: true,
    queueCount: 2,
    hospitalName: "Fortis Flt Lt Rajan Dhall Hospital, Vasant Kunj - Best Hospital in New Delhi",
    waitTimeMin: 12,
    imageUrl: "https://images.unsplash.com/photo-1594824813573-246434de83fb?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-77",
    name: "Dr. Nafees Khan",
    specialty: "General Physician",
    rating: 4.7,
    experience: 23,
    patientsServed: 18000,
    online: true,
    queueCount: 3,
    hospitalName: "Holy Family Hospital",
    waitTimeMin: 15,
    imageUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-78",
    name: "Dr. Ramesh Kumar",
    specialty: "General Physician",
    rating: 4.6,
    experience: 31,
    patientsServed: 31000,
    online: true,
    queueCount: 4,
    hospitalName: "Safdarjung Hospital",
    waitTimeMin: 25,
    imageUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-79",
    name: "Dr. Poonam Khera",
    specialty: "General Physician",
    rating: 4.8,
    experience: 20,
    patientsServed: 15500,
    online: true,
    queueCount: 1,
    hospitalName: "CK Birla Hospital, Delhi",
    waitTimeMin: 10,
    imageUrl: "https://images.unsplash.com/photo-1594824813573-246434de83fb?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "doc-80",
    name: "Dr. Rohit Gupta",
    specialty: "General Physician",
    rating: 4.6,
    experience: 14,
    patientsServed: 11200,
    online: true,
    queueCount: 2,
    hospitalName: "Max Hospital Vaishali",
    waitTimeMin: 15,
    imageUrl: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80"
  }
];

export const appointments: any[] = [
  {
    id: "app-101",
    patientId: "patient-default",
    patientName: "Raghav Ram",
    doctorId: "doc-1",
    doctorName: "Dr. Rajesh Sharma",
    specialty: "Primary Care / Family Physician",
    date: "2026-05-29",
    time: "10:30 AM",
    status: "ACCEPTED",
    symptoms: "Fever and smog cough since yesterday afternoon",
    type: "VIRTUAL"
  }
];

export const queueTokens: any[] = [
  {
    id: "q-1",
    tokenNumber: "GP-034",
    patientId: "patient-123",
    patientName: "Robert Miller",
    doctorId: "doc-1",
    doctorName: "Dr. Rajesh Sharma",
    estimatedWaitTimeMin: 10,
    status: "WAITING",
    checkpointTime: "09:05 AM"
  },
  {
    id: "q-2",
    tokenNumber: "GP-035",
    patientId: "patient-456",
    patientName: "Emily Watson",
    doctorId: "doc-1",
    doctorName: "Dr. Rajesh Sharma",
    estimatedWaitTimeMin: 20,
    status: "WAITING",
    checkpointTime: "09:12 AM"
  }
];

export const medicalRecords: any[] = [
  {
    id: "rec-1",
    patientId: "patient-default",
    date: "2026-03-12",
    title: "Annual Cardiovascular Screening",
    doctorName: "Dr. Naresh Trehan",
    diagnoseSummary: "Electrocardiogram yields regular sinus rhythm. Blood pressure is stable at 118/76. Encouraged regular walking tracks in Chanakyapuri.",
    attachmentName: "cardio-report-2026.pdf"
  },
  {
    id: "rec-2",
    patientId: "patient-default",
    date: "2026-04-05",
    title: "Acute Throat Respiratory Treatment",
    doctorName: "Dr. Rajesh Sharma",
    diagnoseSummary: "Bacterial pharyngitis diagnosed, compounded by local winter smog conditions. Prescribed Amoxicillin sequence and saline gargles.",
    attachmentName: "throat_swab_p231.pdf"
  }
];

let prescriptions: any[] = [
  {
    id: "rx-901",
    appointmentId: "app-101",
    patientId: "patient-default",
    patientName: "Raghav Ram",
    doctorId: "doc-1",
    doctorName: "Dr. Rajesh Sharma",
    date: "2026-05-28",
    diagnosis: "Arid smog allergies and mild bronchial hyper-responsiveness",
    medicines: [
      { name: "Paracetamol 650mg (Crocin)", dosage: "650 mg", frequency: "Three times daily after meals if high temperature", duration: "3 days" },
      { name: "Montelukast & Levocetirizine", dosage: "10 mg / 5 mg", frequency: "Daily before sleep", duration: "10 days" }
    ],
    instructions: "Stay indoors during high AQI index mornings. Use heavy-duty N95 mask. Keep air purifiers running."
  }
];

export const medicineProducts = [
  {
    id: "med-1",
    name: "Crocin Advance 650mg (Paracetamol)",
    category: "PAINKILLER",
    price: 35.0,
    stock: 250,
    description: "Symptomatic relief of fever, headaches, and general somatic body pain.",
    requiresPrescription: false,
    dosageForm: "Tablet",
    imageUrl: "/src/assets/images/crocin_advance_650mg_1780136980034.png",
    pillsColor: "Pure White",
    pillsShape: "Circular / Round",
    pillsMarkings: "Smooth"
  },
  {
    id: "med-2",
    name: "Augmentin 625 Duo (Antibiotic)",
    category: "ANTIBIOTIC",
    price: 180.0,
    stock: 90,
    description: "Amoxicillin and Potassium Clavulanate tablet for bacterial respiratory & throat infections.",
    requiresPrescription: true,
    dosageForm: "Tablet",
    imageUrl: "/src/assets/images/augmentin_625_duo_1780136999177.png",
    pillsColor: "Pure White",
    pillsShape: "Oval / Oblong",
    pillsMarkings: "Central Score Line"
  },
  {
    id: "med-3",
    name: "Atorva 10mg (Atorvastatin)",
    category: "CARDIO",
    price: 124.5,
    stock: 120,
    description: "Lowers bad cholesterol levels and safeguards cardiovascular health.",
    requiresPrescription: true,
    dosageForm: "Tablet",
    imageUrl: "/src/assets/images/atorva_10mg_pill_1780137020258.png",
    pillsColor: "Off-White / Cream",
    pillsShape: "Round",
    pillsMarkings: "AT 10 Imprinted"
  },
  {
    id: "med-4",
    name: "Allegra 120mg (Fexofenadine)",
    category: "FIRST_AID",
    price: 150.0,
    stock: 85,
    description: "Highly effective non-drowsy relief for smog, pollen, and airborne dust allergies.",
    requiresPrescription: false,
    dosageForm: "Tablet",
    imageUrl: "/src/assets/images/allegra_120mg_pill_1780137038900.png",
    pillsColor: "Peach / Pale Pink",
    pillsShape: "Oval / Oblong",
    pillsMarkings: "AL 120 Imprinted"
  },
  {
    id: "med-5",
    name: "Limcee 500mg Chewable (Vitamin C)",
    category: "VITAMINS",
    price: 45.0,
    stock: 300,
    description: "Essential defense nutrition, boosting immunity against airborne conditions.",
    requiresPrescription: false,
    dosageForm: "Tablet",
    imageUrl: "/src/assets/images/limcee_500mg_vitamin_1780137057500.png",
    pillsColor: "Orange / Peach Orange",
    pillsShape: "Round Chewable",
    pillsMarkings: "Citrus Emblem"
  },
  {
    id: "med-6",
    name: "Glycomet SR 500mg (Metformin)",
    category: "CHRONIC",
    price: 95.0,
    stock: 140,
    description: "Sustained-release diabetes formulation for regulating optimal blood sugar levels.",
    requiresPrescription: true,
    dosageForm: "Tablet",
    imageUrl: "/src/assets/images/glycomet_sr_500mg_1780137074831.png",
    pillsColor: "White",
    pillsShape: "Oblong / Capsule-Shaped",
    pillsMarkings: "SR Imprinted"
  },
  {
    id: "med-7",
    name: "Dolo 650mg (Paracetamol)",
    category: "PAINKILLER",
    price: 30.9,
    stock: 500,
    description: "The gold-standard antipyretic & analgesic across India for fever and acute body aches.",
    requiresPrescription: false,
    dosageForm: "Tablet",
    imageUrl: "https://www.netmeds.com/images/product-v1/600x600/341494/dolo_650_mg_tablet_15s_0_1.jpg",
    pillsColor: "Pure White",
    pillsShape: "Capsule-shaped",
    pillsMarkings: "DOLO 650"
  },
  {
    id: "med-8",
    name: "Combiflam (Ibuprofen + Paracetamol)",
    category: "PAINKILLER",
    price: 42.5,
    stock: 320,
    description: "Highly popular anti-inflammatory combination tablet for severe headache, muscle strain, and joint pains.",
    requiresPrescription: false,
    dosageForm: "Tablet",
    imageUrl: "https://www.netmeds.com/images/product-v1/600x600/102011/combiflam_tablet_20s_0_1.jpg",
    pillsColor: "Pure White",
    pillsShape: "Oblong / Capsule-shaped",
    pillsMarkings: "CFL 400"
  },
  {
    id: "med-9",
    name: "Pan-D (Pantoprazole + Domperidone)",
    category: "FIRST_AID",
    price: 165.0,
    stock: 180,
    description: "Dual-action capsule for chronic acid reflux, gastroesophageal reflux disease (GERD), and indigestion.",
    requiresPrescription: true,
    dosageForm: "Capsule",
    imageUrl: "https://www.netmeds.com/images/product-v1/600x600/325178/pan_d_capsule_15s_0_1.jpg",
    pillsColor: "Yellow and White",
    pillsShape: "Capsule",
    pillsMarkings: "PAN-D"
  },
  {
    id: "med-10",
    name: "Thyronorm 50mcg (Thyroxine)",
    category: "CHRONIC",
    price: 145.0,
    stock: 200,
    description: "Hormonal replacement therapy for patients suffering from hypothyroidism in India.",
    requiresPrescription: true,
    dosageForm: "Tablet",
    imageUrl: "https://www.netmeds.com/images/product-v1/600x600/113702/thyronorm_50mcg_tablet_120s_0_1.jpg",
    pillsColor: "Off-White",
    pillsShape: "Round / Tiny",
    pillsMarkings: "50"
  },
  {
    id: "med-11",
    name: "Azithral 500mg (Azithromycin)",
    category: "ANTIBIOTIC",
    price: 119.5,
    stock: 150,
    description: "Broad-spectrum macrolide antibiotic commonly used for chest, throat, and nasal bacterial infections.",
    requiresPrescription: true,
    dosageForm: "Tablet",
    imageUrl: "https://www.netmeds.com/images/product-v1/600x600/113543/azithral_500mg_tablet_5s_0_1.jpg",
    pillsColor: "Light Blue",
    pillsShape: "Oval / Oblong",
    pillsMarkings: "AZI 500"
  },
  {
    id: "med-12",
    name: "Becosules Capsules (Vitamin B-Complex)",
    category: "VITAMINS",
    price: 52.0,
    stock: 450,
    description: "Enriched B-Complex and Vitamin C formula for mouth ulcers, fatigue, and nutritional support.",
    requiresPrescription: false,
    dosageForm: "Capsule",
    imageUrl: "https://www.netmeds.com/images/product-v1/600x600/304156/becosules_capsules_20_s_0_0.jpg",
    pillsColor: "Red and Black",
    pillsShape: "Capsule",
    pillsMarkings: "BCOSL"
  },
  {
    id: "med-13",
    name: "Telma 40mg (Telmisartan)",
    category: "CARDIO",
    price: 98.0,
    stock: 220,
    description: "Angiotensin receptor blocker used to manage high blood pressure and prevent cardiac strokes.",
    requiresPrescription: true,
    dosageForm: "Tablet",
    imageUrl: "https://www.netmeds.com/images/product-v1/600x600/323577/telma_40mg_tablet_30s_0_1.jpg",
    pillsColor: "White",
    pillsShape: "Oval",
    pillsMarkings: "T 40"
  },
  {
    id: "med-14",
    name: "Shelcal 500mg (Calcium + Vit D3)",
    category: "VITAMINS",
    price: 131.0,
    stock: 240,
    description: "Highly recommended bone-density optimizer containing natural elemental calcium and Vitamin D3.",
    requiresPrescription: false,
    dosageForm: "Tablet",
    imageUrl: "https://www.netmeds.com/images/product-v1/600x600/341381/shelcal_500mg_tablet_15s_0_1.jpg",
    pillsColor: "White",
    pillsShape: "Oval",
    pillsMarkings: "SHELCAL"
  },
  {
    id: "med-15",
    name: "Rosuvas 10mg (Rosuvastatin)",
    category: "CARDIO",
    price: 164.0,
    stock: 120,
    description: "Modern cholesterol-regulator that actively blocks HMG-CoA reductase to secure artery walls.",
    requiresPrescription: true,
    dosageForm: "Tablet",
    imageUrl: "https://www.netmeds.com/images/product-v1/600x600/15152/rosuvas_10mg_tablet_10s_0_1.jpg",
    pillsColor: "Yellow",
    pillsShape: "Round",
    pillsMarkings: "R 10"
  },
  {
    id: "med-16",
    name: "Zyloric 100mg (Allopurinol)",
    category: "CHRONIC",
    price: 32.5,
    stock: 190,
    description: "Uric-acid inhibitor commonly prescribed in India for managing gout and recurring kidney stones.",
    requiresPrescription: true,
    dosageForm: "Tablet",
    imageUrl: "https://www.netmeds.com/images/product-v1/600x600/113726/zyloric_100mg_tablet_10s_0_1.jpg",
    pillsColor: "White",
    pillsShape: "Round",
    pillsMarkings: "ZY 100"
  },
  {
    id: "med-17",
    name: "Taxim-O 200mg (Cefixime)",
    category: "ANTIBIOTIC",
    price: 104.2,
    stock: 130,
    description: "Third-generation cephalosporin antibiotic used extensively for urinary tract and typhoidal infections.",
    requiresPrescription: true,
    dosageForm: "Tablet",
    imageUrl: "https://www.netmeds.com/images/product-v1/600x600/324151/taxim_o_200mg_tablet_10s_0_1.jpg",
    pillsColor: "White",
    pillsShape: "Oval",
    pillsMarkings: "TXM 200"
  },
  {
    id: "med-18",
    name: "Omez 20mg (Omeprazole)",
    category: "FIRST_AID",
    price: 68.0,
    stock: 350,
    description: "Time-tested proton-pump inhibitor providing 24-hour relief from excessive acidity and peptic ulcers.",
    requiresPrescription: false,
    dosageForm: "Capsule",
    imageUrl: "https://www.netmeds.com/images/product-v1/600x600/113697/omez_20mg_capsules_20_s_0_0.jpg",
    pillsColor: "Yellow and Green",
    pillsShape: "Capsule",
    pillsMarkings: "OMEZ 20"
  },
  {
    id: "med-19",
    name: "Montair LC (Montelukast + Levocetirizine)",
    category: "FIRST_AID",
    price: 210.0,
    stock: 160,
    description: "Superior combined antihistamine and anti-leukotriene tablet for chronic asthma, smog-cough, and rhinitis.",
    requiresPrescription: true,
    dosageForm: "Tablet",
    imageUrl: "https://www.netmeds.com/images/product-v1/600x600/113615/montair_lc_tablet_10s_0_1.jpg",
    pillsColor: "Beige / Pale Orange",
    pillsShape: "Round",
    pillsMarkings: "M LC"
  },
  {
    id: "med-20",
    name: "Liv.52 Tablets (Himalaya)",
    category: "CHRONIC",
    price: 170.0,
    stock: 400,
    description: "Famous Ayurvedic hepatoprotective formulation supporting optimal liver function and metabolic recovery.",
    requiresPrescription: false,
    dosageForm: "Tablet",
    imageUrl: "https://www.netmeds.com/images/product-v1/600x600/348332/liv_52_tablet_100s_0_0.jpg",
    pillsColor: "Brown",
    pillsShape: "Round / Uncoated",
    pillsMarkings: "L52"
  },
  {
    id: "med-21",
    name: "Amlong 5mg (Amlodipine)",
    category: "CARDIO",
    price: 32.0,
    stock: 300,
    description: "Calcium channel blocker that relaxes arterial walls, managing high blood pressure and angina symptoms.",
    requiresPrescription: true,
    dosageForm: "Tablet",
    imageUrl: "https://www.netmeds.com/images/product-v1/600x600/323145/amlong_5mg_tablet_15s_0_1.jpg",
    pillsColor: "White",
    pillsShape: "Octagonal / Custom",
    pillsMarkings: "AML 5"
  },
  {
    id: "med-22",
    name: "Ciplox 500mg (Ciprofloxacin)",
    category: "ANTIBIOTIC",
    price: 45.4,
    stock: 220,
    description: "Fluoroquinolone antibiotic designed to wipe out stubborn gastrointestinal and urinary bacterial infections.",
    requiresPrescription: true,
    dosageForm: "Tablet",
    imageUrl: "https://www.netmeds.com/images/product-v1/600x600/113576/ciplox_500mg_tablet_10s_0_1.jpg",
    pillsColor: "White",
    pillsShape: "Oval",
    pillsMarkings: "CIPLOX 500"
  },
  {
    id: "med-23",
    name: "Saridon (Triple Action Pain Relief)",
    category: "PAINKILLER",
    price: 48.0,
    stock: 480,
    description: "Propended formula mapping Paracetamol, Propyphenazone, and Caffeine specifically to resolve acute severe headaches.",
    requiresPrescription: false,
    dosageForm: "Tablet",
    imageUrl: "https://www.netmeds.com/images/product-v1/600x600/104344/saridon_tablet_10s_0_1.jpg",
    pillsColor: "White",
    pillsShape: "Round",
    pillsMarkings: "S"
  },
  {
    id: "med-24",
    name: "Eldoper 2mg (Loperamide)",
    category: "FIRST_AID",
    price: 26.0,
    stock: 250,
    description: "Fast-acting anti-diarrheal formulation mapping gut motility receptors for immediate symptomatic control.",
    requiresPrescription: false,
    dosageForm: "Capsule",
    imageUrl: "https://www.netmeds.com/images/product-v1/600x600/323164/eldoper_2mg_capsule_10s_0_1.jpg",
    pillsColor: "Green and Grey",
    pillsShape: "Capsule",
    pillsMarkings: "ELD 2"
  },
  {
    id: "med-25",
    name: "Pantocid 40mg (Pantoprazole)",
    category: "FIRST_AID",
    price: 155.0,
    stock: 280,
    description: "Highly stable, rapid-onset proton pump inhibitor used to neutralize stomach acids and soothe heartburn.",
    requiresPrescription: true,
    dosageForm: "Tablet",
    imageUrl: "https://www.netmeds.com/images/product-v1/600x600/324141/pantocid_40mg_tablet_15s_0_1.jpg",
    pillsColor: "Lemon Yellow",
    pillsShape: "Oval",
    pillsMarkings: "PANTO 40"
  },
  {
    id: "med-26",
    name: "Neurobion Forte (Vitamin B Complex)",
    category: "VITAMINS",
    price: 38.5,
    stock: 600,
    description: "India's highest-selling therapeutic Vitamin B complex for nerve nourishment, neuropathy, and active systemic recovery.",
    requiresPrescription: false,
    dosageForm: "Tablet",
    imageUrl: "https://www.netmeds.com/images/product-v1/600x600/104328/neurobion_forte_tablet_30s_0_1.jpg",
    pillsColor: "Bright Pink",
    pillsShape: "Round / Sugar Coated",
    pillsMarkings: "N"
  },
  {
    id: "med-27",
    name: "Volini Gel (Diclofenac Pain Relief)",
    category: "FIRST_AID",
    price: 110.0,
    stock: 190,
    description: "Effective topical gel containing Diclofenac Diethylamine, Methyl Salicylate, and Menthol for neck, shoulder, and knee joint pains.",
    requiresPrescription: false,
    dosageForm: "Gel",
    imageUrl: "https://www.netmeds.com/images/product-v1/600x600/102029/volini_pain_relief_gel_15gm_0_1.jpg",
    pillsColor: "Clear Gel",
    pillsShape: "Tube",
    pillsMarkings: "N/A"
  },
  {
    id: "med-28",
    name: "Cremaffin Syrup (Mint Flavour)",
    category: "FIRST_AID",
    price: 240.0,
    stock: 140,
    description: "Gentle and effective laxative emulsion mapping Liquid Paraffin and Milk of Magnesia for immediate relief of chronic constipation.",
    requiresPrescription: false,
    dosageForm: "Syrup",
    imageUrl: "https://www.netmeds.com/images/product-v1/600x600/102718/cremaffin_mint_liquid_225ml_0_1.jpg",
    pillsColor: "White Liquid",
    pillsShape: "Bottle",
    pillsMarkings: "N/A"
  },
  {
    id: "med-29",
    name: "Ascoril LS Syrup (Cough Expectorant)",
    category: "FIRST_AID",
    price: 135.0,
    stock: 170,
    description: "Clinical mucolytic respiratory liquid that thins thick congestive phlegm, easing smog-allergy breaths.",
    requiresPrescription: true,
    dosageForm: "Syrup",
    imageUrl: "https://www.netmeds.com/images/product-v1/600x600/323315/ascoril_ls_syrup_100ml_0_1.jpg",
    pillsColor: "Amber Liquid",
    pillsShape: "Bottle",
    pillsMarkings: "N/A"
  },
  {
    id: "med-30",
    name: "Zincovit (Multivitamins & Minerals)",
    category: "VITAMINS",
    price: 115.0,
    stock: 350,
    description: "Premium daily health supplement loaded with essential trace elements like zinc, maintaining general respiratory immunity.",
    requiresPrescription: false,
    dosageForm: "Tablet",
    imageUrl: "https://www.netmeds.com/images/product-v1/600x600/304153/zincovit_tablet_15s_0_0.jpg",
    pillsColor: "Grape/Dark Red",
    pillsShape: "Oval",
    pillsMarkings: "ZINCO"
  },
  {
    id: "med-31",
    name: "Jalra-M 50/500 (Vildagliptin + Metformin)",
    category: "CHRONIC",
    price: 280.0,
    stock: 140,
    description: "Premium anti-diabetic combination therapy that optimizes pancreatic insulin release and limits hepatic glucose.",
    requiresPrescription: true,
    dosageForm: "Tablet",
    imageUrl: "https://www.netmeds.com/images/product-v1/600x600/388049/jalra_m_50mg_500mg_tablet_15s_0_1.jpg",
    pillsColor: "Light Yellow",
    pillsShape: "Oblong",
    pillsMarkings: "JALRA"
  }
];

export const medicineOrders: any[] = [];
export const emergencyAlerts: any[] = [];
export const activeChats: { [appId: string]: any[] } = {};